/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec.uploader.dropbox;

import com.iexec.uploader.dropbox.uploader.UploaderService;
import com.iexec.uploader.dropbox.utils.FilesUtils;

import static com.iexec.uploader.dropbox.signer.SignerService.signEnclaveChallengeAndWriteSignature;
import static com.iexec.uploader.dropbox.uploader.UploaderService.DROPBOX_STORAGE;
import static com.iexec.uploader.dropbox.utils.EnvUtils.getEnvVarOrExit;

//TODO 1 - Rename Github: dropbox-uploader -> tee-post-compute
//TODO 2 - @Slf4j
public class App {

    public static void main(String[] args) {
        System.out.println("Tee-post-compute started");
        System.out.println("(Uploader & Signer)");

        System.out.println("DEBUG - env: " + System.getenv().toString());

        System.out.println("Uploader started");
        String storageLocation = getEnvVarOrExit("IEXEC_REQUESTER_STORAGE_LOCATION");

        boolean isUploaded;

        switch (storageLocation) {
            case DROPBOX_STORAGE:
                isUploaded = uploadWithDropbox();
                break;
            default:
                System.out.println("Default result storage provider");
                isUploaded = uploadWithDropbox();
                break;
        }

        if (!isUploaded) {
            System.err.println("Uploader failed (exiting)");
            System.exit(1);
        } else {
            System.out.println("Uploaded!");
        }

        System.out.println("Signer started");
        String teeChallengePrivateKey = getEnvVarOrExit("TEE_CHALLENGE_PRIVATE_KEY");
        String taskId = getEnvVarOrExit("TASK_ID");
        String workerAddress = getEnvVarOrExit("WORKER_ADDRESS");

        boolean isSignatureFileCreated = signEnclaveChallengeAndWriteSignature(teeChallengePrivateKey, taskId, workerAddress);
        if (!isSignatureFileCreated) {
            System.err.println("Signer failed (exiting)");
            System.exit(1);
        } else {
            System.out.println("Signed!");
        }

        System.exit(0);
    }

    private static boolean uploadWithDropbox() {
        System.out.println("Will use Dropbox");
        String taskId = getEnvVarOrExit("TASK_ID");
        String dropboxAccessToken = getEnvVarOrExit("DROPBOX_ACCESS_TOKEN");
        String remoteFilename = taskId + ".zip";

        return UploaderService.uploadToDropBox(FilesUtils.getResultFilePath(taskId), dropboxAccessToken, remoteFilename);
    }


}
