/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec.worker.tee.post.compute;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Main {

    static PostComputeAppRunner postComputeAppRunner;

    private Main() {
    }

    public static void main(String[] args) {
        final int exitCode = getPostComputeAppRunner().start();
        System.exit(exitCode);
    }

    static PostComputeAppRunner getPostComputeAppRunner() {
        return postComputeAppRunner == null
                ? new PostComputeAppRunner()
                : postComputeAppRunner;
    }
}
