/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec.worker.tee.post.compute;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Main {

    private Main() {
    }

    public static void main(String[] args) {
        new PostComputeAppRunner().start();
    }
}
